image: openjdk:17-alpine

stages:
  - build
  - test
  - deploy

before_script:
  - apk update && apk add findutils # required for build and test scripts (./gradlew bootJar, ./gradlew test  use 'xargs')

build:
  stage: build
  only:
    - master
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - echo "Here might be the deployment of the application"

after_script:
  - echo "End of CI"